routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home')->name('home');

Route::get('/detail/{slug}', 'HomeController@detail')->name('detail');

Route::get('/hello/{student}', "HelloController@index")->name('hello.name');
Route::get('/hello', "HelloController@hello")->name('hello');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('/posts', 'PostController') ;
});


Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    /**
     * Get the post that owns the comment.
     */
    public function posts()
    {
        return $this->hasMany('App\Post');
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    protected $guarded = [];
    /**
     * Get the post that owns the comment.
     */
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    /**
     * The tags that belong to the post.
     */
    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }
}

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','role', 'username', 'email', 'password',
    ];


    //protected $table = "users";



    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HelloController.php
<?php

namespace App\Http\Controllers;

use http\Env\Response;
use http\Url;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;

class HelloController extends Controller
{
    public function __construct()
    {
        $this->middleware("Ip") ;
    }

    public function index($student){
        $students = ['Alassane', 'Cheikh', 'Penda'] ;

        array_push($students, $student);

        //return Response()->json($students)

        return view('hello.index', compact("students")) ;
    }

    public function hello(){

        $students = ['Alassane', "Cheikh", "Penda"] ;
        return view('hello.index',compact("students")) ;
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }

    public function home(){
        $recent_posts = Post::orderBy('id', 'desc')->limit(5)->get();
        return view('home.index', compact('recent_posts'));
    }

    public function detail($slug){
        $post = Post::where('slug', $slug)->first() ;
        return view("home.detail", compact('post'));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class PostController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all() ;

        return view('posts.index', compact("posts"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return  view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputs = $request->all();

        $imageName = time().'.'.request()->media->getClientOriginalExtension();
        request()->media->move(public_path('images'), $imageName);

        $inputs['media'] = $imageName;
        $inputs['slug'] = Str::slug($request->title);
        $inputs['user_id'] = Auth::user()->id;

        if ($request->status == 'on'){

            $inputs['status'] = 1;
        }else{

            $inputs['status'] = 0;
        }

        unset($inputs["_token"]);

        Post::create($inputs) ;

        return redirect(route('posts.index'))->with('success', 'Votre article a été bien ajouté');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id){

        $post = Post::find($id);

//        dd($post);
        return view('posts.edit', compact(['post']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
//        dd($request->all());

        $post = Post::find($id);

        $inputs = $request->all();

        if(file_exists($request->file('media'))){
//            dd($request->file('media'));
            $imageName = time().'.'.request()->media->getClientOriginalExtension();
            request()->media->move(public_path('images'), $imageName);

            $inputs['media'] = $imageName;
        }

        unset($inputs['_token']);


        $inputs['slug'] = Str::slug($inputs["title"]);

        if ($request->status == 'on'){

            $inputs['status'] = 1;
        }else{

            $inputs['status'] = 0;
        }

        $post->title = $inputs['title'];
        $post->content = $inputs['content'];
        $post->slug = $inputs['slug'];
        $post->date_publication = $post->date_publication;
        $post->status = $inputs['status'];

//        dd($inputs);

        $post->save();

        return redirect(route("posts.index"));



    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        $post->status = 0 ;
        $post->save() ;

        return redirect(route("posts.index"))->with('success', "Article non trouvé");

        if($post){
            $post->delete();
            return redirect(route("posts.index"))->with('success', "Article supprimé");
        }
    }
}

resources/views/hello/index.blade.php
@extends("layout")

@section("content")
    <h1>Hello world !</h1>

    <ul>
        @foreach($students as $student)
            <li>
                @if($student != "Alassane")
                {{ $student }} est un étudiant
                    @else
                    {{ $student }} <b style="color: darkgreen">est l'assistant</b>
                    @endif
            </li>
        @endforeach
    </ul>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!


                    {{ Auth::user()->username }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home/detail.blade.php
@extends('layout')

@section("slideshow")
@endsection

@section('content')
    <div class="row">
        <div class="col-4">
            <img class="img-thumbnail" src="{{ $post->media }}" alt="">

        </div>
        <div class="col-8">
            <h3>{{ $post->title }}</h3>
            <p>
                {{ $post->content }}
            </p>
        </div>
    </div>
@endsection

resources/views/home/index.blade.php
@extends('layout')

@section('title')
    Bienvenue
@endsection
@section('content')

    <div class="row">
        <div class="col-8">

            <h3>Liste des derniers articles</h3>
            @foreach($recent_posts as $recent_post)


                <div class="card mb-3">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img src="{{ $recent_post->media }}" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ $recent_post->title }}</h5>
                                <p class="card-text">
                                    {{ $recent_post->content }}
                                </p>
                                <p class="card-text">
                                    <small class="text-muted">
                                        <a href="{{ route('detail', $recent_post->slug) }}">
                                            Voir plus
                                        </a>
                                    </small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

            @endforeach
        </div>
        <div class="col-4">
            <h3>La liste des catégories</h3>
        </div>
    </div>
@endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Note Blog - @yield('title')</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
</head>
<body>
        <div class="container">
            @include('partials.navbar')
            @section('slideshow')
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img height="400" src="https://www.parkingdakar.com/public/uploads/annonces/1552347405.jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img height="400" src="https://www.parkingdakar.com/storage/app/public/uploads/annonces/51bb85c40769f738c3087c6a5bfdc268.jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img height="400" src="https://www.parkingdakar.com/storage/app/public/uploads/annonces/be2887aae115fa52459a6cc6805e533d.jpg" class="d-block w-100" alt="...">
                        </div>
                    </div>
                </div>
            @show
            @yield('content')
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ route('home') }}">Notre Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>

            <li class="nav-item">
                <a href="{{ route("login") }}" class="nav-link">Se connecter</a>
            </li>
        </ul>

        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <form action="{{ route('posts.store') }}" method="post" enctype="multipart/form-data" >
            @csrf
            <div class="form-group">
                <label for="exampleInputEmail1">Titre</label>
                <input name="title" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ex : Macky SAll">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                <label for="">Contenu</label>
                <textarea name="content" id="" class="form-control">

                </textarea>
            </div>
            <div class="form-group">
                <label for="">Media</label>
                <input type="file" name="media" class="form-control">
            </div>
            <div class="form-group">
                <label for="">Date de publication</label>
                <input type="datetime-local" class="form-control" name="date_publication">
            </div>

            <div class="form-group form-check">
                <input name="status" type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Statut</label>
            </div>
            <button type="submit" class="btn btn-success">Envoyer</button>
        </form>
    </div>
</div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <form action="{{ route('posts.update', $post->id) }}" method="post" enctype="multipart/form-data" >
                @csrf
                {{ method_field('PATCH') }}
                <div class="form-group">
                    <label for="exampleInputEmail1">Titre</label>
                    <input value="{{ $post->title }}" name="title" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ex : Macky SAll">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="">Contenu</label>
                    <textarea name="content" id="" class="form-control">{{ $post->content }}</textarea>
                </div>
                <div class="form-group">
                    <label for="">Media</label>
                    <img style="height: 40px;" src="{{ asset($post->media) }}" alt="">
                    <input type="file" name="media" class="form-control">
                </div>
                <div class="form-group">
                    <label for="">Date de publication</label>
                    <input value="{{ $post->date_publication }}" type="datetime-local" class="form-control" name="date_publication">
                </div>

                <div class="form-group form-check">
                    <input @if($post->status == 1) checked @endif name="status" type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label  class="form-check-label" for="exampleCheck1">Statut</label>
                </div>
                <button type="submit" class="btn btn-success">Envoyer</button>
            </form>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if(Session()->get('success'))
            <label class="alert alert-success">
                {{ Session()->get('success') }}
            </label>
        @endif
        <a href="{{ route('posts.create') }}" class="btn btn-primary">
            Ajouter un nouveau
        </a>
        <div class="row col-12">
            <table class="table">
                <thead>
                <tr>
                    <th>Titre</th>
                    <th>Date de publication</th>
                    <th>Actions</th>
                </tr>
                </thead>

                <tbody>
                @foreach($posts as $post)
                    @if($post->status == 1)
                    <tr>
                        <td>{{ $post->title }}</td>
                        <td>{{ $post->date_publication }}</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <button type="button" class="btn btn-primary">View</button>
                                <a href="{{ route("posts.edit", $post->id) }}" type="button" class="btn btn-warning">Edit</a>

                                <form action="{{ route('posts.destroy', $post->id) }}" method="post">
                                    @csrf
                                    {{ method_field('DELETE') }}
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endif
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection